name: Multiline Output

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  output:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: createSetParameter
        id: set
        run:
          echo "OUT<<EOT" >> "$GITHUB_OUTPUT"
          echo [ >> "$GITHUB_OUTPUT"
          echo \"image.repository=${{ steps.login-ecr.outputs.registry }}/${{env.CONTAINER_REPO}}\"
          echo ] >> "$GITHUB_OUTPUT"
          echo EOT >> "$GITHUB_OUTPUT"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ steps.set.outputs.OUT }}
          echo test, and deploy your project.
