name: Multiline Output

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  output:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set the value in bash
        id: step_one
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "JSON_RESPONSE<<$EOF" >> "$GITHUB_OUTPUT"
          echo hihi >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
          echo "NASE=hase" >> "$GITHUB_OUTPUT"
      
#      - name: createSetParameter
#        id: set
#        run:
#          echo "OUT<<EOT" >> "$GITHUB_OUTPUT"
#          echo [ >> "$GITHUB_OUTPUT"
#          echo \"image.repository=${{ steps.login-ecr.outputs.registry }}/${{env.CONTAINER_REPO}}\"
#          echo ] >> "$GITHUB_OUTPUT"
#          echo "EOT" >> "$GITHUB_OUTPUT"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ steps.set.step_one.JSON_RESPONSE }}
          echo ${{ steps.set.step_one.NASE }}
          echo test, and deploy your project.
