name: Multiline Output

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      sidecarImage:
        type: string
        required: false

jobs:
  output:
    runs-on: ubuntu-latest
#          if [ -n ${{inputs.sidecarImage}} ]
#            then
#              echo \"sidecar.container[0].image=${{inputs.sidecarImage}}\" >> "$GITHUB_OUTPUT"
#          fi
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set the value in bash
        id: step_one
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "JSON_RESPONSE<<EOF" >> "$GITHUB_OUTPUT"
          echo [ >> "$GITHUB_OUTPUT"
          echo \"hase=nase\", >> "$GITHUB_OUTPUT"

          echo \"dings=bums\" >> "$GITHUB_OUTPUT"
          echo ] >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
          echo "NASE=hase" >> "$GITHUB_OUTPUT"
      
#      - name: createSetParameter
#        id: set
#        run:
#          echo "OUT<<EOT" >> "$GITHUB_OUTPUT"
#          echo [ >> "$GITHUB_OUTPUT"
#          echo \"image.repository=${{ steps.login-ecr.outputs.registry }}/${{env.CONTAINER_REPO}}\"
#          echo ] >> "$GITHUB_OUTPUT"
#          echo "EOT" >> "$GITHUB_OUTPUT"
     
          
      - name: outputs
        run: |
          echo ${{ inputs.sidecarImage && '"sidecar.container[0].image='}}${{inputs.sidecarImage}}${{inputs.sidecarImage && '"'}}

          echo ${{ join(fromJSON(steps.step_one.outputs.JSON_RESPONSE), ':') }}
     
